import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';

@Component({
  selector: 'app-survey-element-add',
  template: `
    <section class="add-more slide-top-enter-animation">
      <div class="add-more-content add-new"> Dodaj pytanie <i nz-icon nzType="plus"></i></div>
      <div style="display: flex; color:rgba(0,0,0,0.6)">
        <div *ngFor="let x of allowed" style="margin: 1.2em; cursor: pointer; display: flex;flex-direction: row" (click)="add.emit(x.factory())" class="hover-add">
          <div>{{x.friendlyName}}<div>
            <i style="display: block;font-size: 2em" nz-icon [nzType]="x.icon"  ></i>
          </div>

          </div>
        </div>
      </div>
    </section>
  `,
  styles: [
    `
      .slide-top-enter-animation {
        /*-webkit-animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) ;*/
        animation: slide-top-enter-animation 0.9s cubic-bezier(0.250, 0.460, 0.450, 0.940) ;
      }
      /* ----------------------------------------------
       * Generated by Animista on 2021-3-19 21:23:20
       * Licensed under FreeBSD License.
       * See http://animista.net/license for more info.
       * w: http://animista.net, t: @cssanimista
       * ---------------------------------------------- */

      /**
       * ----------------------------------------
       * animation slide-top
       * ----------------------------------------
       */

      @keyframes slide-top {
        0% {
          /*-webkit-transform: translateY(0);*/
          transform: translateY(0) scale(1);
        }
        100% {
          /*-webkit-transform: translateY(-7px);*/
          transform: translateY(-7px) scale(1);
        }
      }

      @keyframes shake {
        0%,
        100% {
          transform: rotate(0deg);
        }
        20%,
        60% {
          transform: rotate(6deg);
        }
        40%,
        80% {
          transform: rotate(-6deg);
        }
      }
      /* ----------------------------------------------
       * Generated by Animista on 2021-3-19 21:44:48
       * Licensed under FreeBSD License.
       * See http://animista.net/license for more info.
       * w: http://animista.net, t: @cssanimista
       * ---------------------------------------------- */

      /**
       * ----------------------------------------
       * animation slide-top
       * ----------------------------------------
       */

      @keyframes slide-top-enter-animation {
        1000% {

          transform: translateY(0);
          opacity: 1;
        }
        0% {

          transform: translateY(100px);
          opacity: 0;
        }
      }
      .add-more{
        margin-top: 4em;
        width: 100%;
        height: 200px;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        border: 3px dashed rgba(0,0,0,0.1);
      }
      .add-more-content{
        display: flex;
        justify-content: center;
        align-items: center;
      }

      .hover-add{
        transition:0.2s  ease-in-out  all;
      }
      .hover-add:hover{
        color:rgba(0,0,0,0.8);
        transform: scale(1.1);
      }
      .add-new{
        color:rgba(0,0,0,0.5);
        font-family: "Open Sans", sans-serif;
      }

    `
  ]
})
export class SurveyElementAddComponent implements OnInit {
  @Input() collection;
  @Input() allowed=[]
  @Output() add = new EventEmitter<()=>()=>void>()
  constructor() { }

  ngOnInit(): void {
  }

}
